[build]
# Dossier principal du projet
path = "."

# Version de Node.js
builder = "node:20.17.0"

[build.args]
# Définir l'environnement de build comme production
env = ["NODE_ENV=production"]

[install]
# Installer les dépendances pour le client et le serveur
commands = [
  "npm install"  # Installe les dépendances à la racine du projet
]

[dev]
# Commande pour démarrer le client et le serveur en mode développement
command = "npm start"  # Utilisation de `npm start` qui lance les deux processus (client + serveur)

[serve]
# Commande pour démarrer l'application en production
command = "npm start"  # Utilisation de `npm start` qui lance les deux processus en production
